version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: proyectotic
      POSTGRES_PASSWORD: tic2024
      POSTGRES_DB: wtfcinemadb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
